<?php

require_once "autoload.php";

$agenda = new Agenda("data.csv");
$id = isset($_GET['id']) ? $_GET['id'] : null;
$patient = $agenda->getVisit($id);

//Cuando hagamos submit, envía por post, ejecuta update de agenda y redirecciona a list.php
if (count($_POST) > 0) {
	$agenda->update($_POST);
	header("location: list.php");
}


?>
<!DOCTYPE html>
<html lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Edit Visit Form</title>
	<link rel="stylesheet" type="text/css" href="./editStyle.css" media="all">
	
</head>

<body id="main_body">

	
	<div id="form_container">

		<h1><a>Edit Visit Form</a></h1>
		<form id="form_36409" class="appnitro" method="post" action="edit.php?id=<?=$id?>">
			<div class="form_description">
				<h2>New Visit Form</h2>
				<p>DAW 23-24</p>
			</div>
			<ul>

				<li id="li_1">
					<label class="description" for="id">ID </label>
					<div>
						<input id="id" name="id" class="element text small" type="text" maxlength="10" value="<?=$patient->getId()?>" />
					</div>
				</li>
				<li id="li_1">
					<label class="description" for="name">Patient Name </label>
					<div>
						<input id="name" name="name" class="element text small" type="text" maxlength="10" value="<?=$patient->getName()?>" />
					</div>
				</li>
				<li id="li_2">
					<label class="description" for="bill">Bill </label>
					<div>
						<input id="bill" name="bill" class="element text medium" type="number" maxlength="255" value="<?=$patient->getBill()?>" />
					</div>
				</li>
				<li id="li_4">
					<label class="description" for="date">Date </label>
					<input id="date" name="date" type="date" value="<?=$patient->getDate()?>"/>
				</li>
				<li id="li_5">
					<span>
						<input id="paid" name="paid" class="element checkbox" type="checkbox" value="1" <?= $patient->getPaid() ? "checked":""; ?>/>
						<label class="choice" for="paid">Paid?</label>
					</span>
				</li>

				<li class="buttons">
					<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
				</li>
			</ul>
		</form>
		<div id="footer">
			Generated by <a href="http://www.daw23-24.org">DAW 23-24</a>
		</div>
	</div>
	
</body>

</html>